# Topics
/graph_visualization:
  ros__parameters:
    sub_local_graph_topic            : /local_graph
    sub_global_graph_topic           : /global_graph
    pub_local_graph_marker_topic     : /local_graph_markers
    pub_global_graph_marker_topic    : /global_graph_markers
